package ens

// ABI vectors for the TypeScript mirror's name resolver (../../mirror/src/names.ts).
//
// The mirror resolves names through the Universal Resolver on whatever eth_call the
// client injected, with hand-rolled ABI encoding, so the blobs it is tested against
// are packed here by go-ethereum from the same ABI the Go tools use rather than
// written by hand. Regenerate with:
//
//	go test ./internal/ens/ -run MirrorFixtures -update-fixtures

import (
	"bytes"
	"encoding/json"
	"flag"
	"math/big"
	"os"
	"testing"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/common/hexutil"

	"github.com/Skanislav/evm-scan/internal/ccip"
)

var updateMirrorFixtures = flag.Bool("update-fixtures", false,
	"rewrite mirror/testdata/names.json from the Universal Resolver ABI")

const mirrorFixturePath = "../../mirror/testdata/names.json"

type nameVector struct {
	Name string `json:"name"`
	Hash string `json:"hash"`
	DNS  string `json:"dns"`
}

type namesFixture struct {
	Note              string       `json:"note"`
	UniversalResolver string       `json:"universal_resolver"`
	Names             []nameVector `json:"names"`

	Resolve struct {
		Name       string `json:"name"`
		Address    string `json:"address"`
		Resolver   string `json:"resolver"`
		Calldata   string `json:"calldata"`
		Returndata string `json:"returndata"`
		// Returndata for a name whose resolver answers addr() with zero.
		ZeroReturndata string `json:"zero_returndata"`
	} `json:"resolve"`

	Reverse struct {
		Address         string `json:"address"`
		CoinType        string `json:"coin_type"`
		Name            string `json:"name"`
		Resolver        string `json:"resolver"`
		ReverseResolver string `json:"reverse_resolver"`
		Calldata        string `json:"calldata"`
		Returndata      string `json:"returndata"`
		// Returndata when the address has no primary name: an empty string.
		EmptyReturndata string `json:"empty_returndata"`
	} `json:"reverse"`

	Reverts struct {
		ResolverNotFound    string   `json:"resolver_not_found"`
		OffchainLookup      string   `json:"offchain_lookup"`
		OffchainURLs        []string `json:"offchain_urls"`
		ReverseMismatch     string   `json:"reverse_mismatch"`
		ReverseMismatchName string   `json:"reverse_mismatch_name"`
		ResolverError       string   `json:"resolver_error"`
		UnsupportedProfile  string   `json:"unsupported_profile"`
	} `json:"reverts"`
}

func buildNamesFixture(t *testing.T) []byte {
	t.Helper()
	must := func(b []byte, err error) []byte {
		t.Helper()
		if err != nil {
			t.Fatal(err)
		}
		return b
	}

	const ur = "0xeEeEEEeE14D718C2B47D9923Deab1335E144EeEe"
	account := common.HexToAddress("0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045")
	resolver := common.HexToAddress("0xae66c62AcAE72098BdAc57d8E8AED53EF000b2Ba")
	reverseResolver := common.HexToAddress("0xA7d635c8de9a58a228AA69353a1699C7Cc240DCF")
	hintAccount := common.HexToAddress("0xAbCdEf0123456789abcdef0123456789ABCDEF01")

	var f namesFixture
	f.Note = "Generated by internal/ens/mirror_fixtures_test.go; do not edit by hand."
	f.UniversalResolver = ur

	for _, name := range []string{"", "eth", "vitalik.eth", HintName(hintAccount, "evmscan.eth", 1, false), HintName(hintAccount, "evmscan.eth", 8453, true)} {
		f.Names = append(f.Names, nameVector{
			Name: name,
			Hash: Namehash(name).Hex(),
			DNS:  hexutil.Encode(DNSEncode(name)),
		})
	}

	// resolve(dns("vitalik.eth"), addr(namehash)) → (abi.encode(address), resolver).
	name := "vitalik.eth"
	profile := must(AddrCallData(Namehash(name)))
	f.Resolve.Name = name
	f.Resolve.Address = account.Hex()
	f.Resolve.Resolver = resolver.Hex()
	f.Resolve.Calldata = hexutil.Encode(must(UniversalResolverABI.Pack("resolve", DNSEncode(name), profile)))
	resolveOut := UniversalResolverABI.Methods["resolve"].Outputs
	f.Resolve.Returndata = hexutil.Encode(must(resolveOut.Pack(must(mustArgs("address").Pack(account)), resolver)))
	f.Resolve.ZeroReturndata = hexutil.Encode(must(resolveOut.Pack(must(mustArgs("address").Pack(common.Address{})), resolver)))

	// reverse(addressBytes, 60) → (primary, resolver, reverseResolver).
	f.Reverse.Address = account.Hex()
	f.Reverse.CoinType = "60"
	f.Reverse.Name = name
	f.Reverse.Resolver = resolver.Hex()
	f.Reverse.ReverseResolver = reverseResolver.Hex()
	f.Reverse.Calldata = hexutil.Encode(must(UniversalResolverABI.Pack("reverse", account.Bytes(), new(big.Int).SetUint64(60))))
	reverseOut := UniversalResolverABI.Methods["reverse"].Outputs
	f.Reverse.Returndata = hexutil.Encode(must(reverseOut.Pack(name, resolver, reverseResolver)))
	f.Reverse.EmptyReturndata = hexutil.Encode(must(reverseOut.Pack("", common.Address{}, common.Address{})))

	revert := func(errName string, vals ...any) string {
		t.Helper()
		e, ok := UniversalResolverABI.Errors[errName]
		if !ok {
			t.Fatalf("no error %s in the Universal Resolver ABI", errName)
		}
		return hexutil.Encode(append(e.ID[:4], must(e.Inputs.Pack(vals...))...))
	}
	f.Reverts.ResolverNotFound = revert("ResolverNotFound", DNSEncode("nobody.eth"))
	f.Reverts.ReverseMismatch = revert("ReverseAddressMismatch", "liar.eth", common.HexToAddress("0x1").Bytes())
	f.Reverts.ReverseMismatchName = "liar.eth"
	f.Reverts.ResolverError = revert("ResolverError", []byte{0xde, 0xad, 0xbe, 0xef})
	f.Reverts.UnsupportedProfile = revert("UnsupportedResolverProfile", [4]byte{0xbc, 0x1c, 0x58, 0xd1})

	// OffchainLookup as a CCIP-Read resolver raises it (ERC-3668), which the Universal
	// Resolver passes through untouched when asked without a gateway.
	urls := []string{"https://gateway.example/{sender}/{data}.json"}
	offchain := must(mustArgs("address", "string[]", "bytes", "bytes4", "bytes").Pack(
		resolver, urls, profile, [4]byte{0xf4, 0xd4, 0xd2, 0xf8}, []byte{0x01}))
	f.Reverts.OffchainLookup = hexutil.Encode(append(ccip.OffchainLookupSelector[:], offchain...))
	f.Reverts.OffchainURLs = urls

	body, err := json.MarshalIndent(&f, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	return append(body, '\n')
}

// TestMirrorFixtures asserts mirror/testdata/names.json is what this package would
// generate now, so a change to the encoding on either side shows up in CI rather than
// as a mirror that quietly resolves the wrong thing.
func TestMirrorFixtures(t *testing.T) {
	want := buildNamesFixture(t)
	if *updateMirrorFixtures {
		if err := os.WriteFile(mirrorFixturePath, want, 0o644); err != nil {
			t.Fatal(err)
		}
		t.Logf("wrote %s", mirrorFixturePath)
		return
	}
	have, err := os.ReadFile(mirrorFixturePath)
	if err != nil {
		t.Fatalf("%v; run with -update-fixtures", err)
	}
	if !bytes.Equal(have, want) {
		t.Fatalf("%s is out of step with the ABI; run: go test ./internal/ens/ -run MirrorFixtures -update-fixtures", mirrorFixturePath)
	}
}
