package api

import (
	"bytes"
	"encoding/json"
	"flag"
	"math/big"
	"os"
	"path/filepath"
	"testing"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/common/hexutil"
	"github.com/ethereum/go-ethereum/crypto"

	"github.com/Skanislav/evm-scan/internal/store"
)

var updateVerdictFixture = flag.Bool("update", false, "rewrite testdata/verdict.json")

// verdictFixture is what testdata/verdict.json holds: fixed inputs and every
// intermediate the page has to reproduce. The private key is a test constant and
// nothing else; the signature is deterministic (RFC 6979) so the file is stable.
type verdictFixture struct {
	Note        string                         `json:"note"`
	PrivateKey  string                         `json:"private_key"`
	Account     string                         `json:"account"`
	ChainID     uint64                         `json:"chain_id"`
	Deadline    string                         `json:"deadline"`
	Verdicts    []verdictPairJSON              `json:"verdicts"`
	Domain      map[string]string              `json:"domain"`
	Types       map[string][]map[string]string `json:"types"`
	Digest      string                         `json:"digest"`
	TypedHash   string                         `json:"eip712_hash"`
	Signature   string                         `json:"signature"`
	RequestBody json.RawMessage                `json:"request_body"`
}

// The pairs are deliberately given out of address order, with the smallest
// address last, so a reader that forgets to sort fails the fixture.
func fixtureInputs() (key string, chainID uint64, deadline *big.Int, pairs []store.Verdict) {
	key = "0x4c0883a69102937d6231471b5dbb6204fe5129617082792ae468d01a3f362318"
	chainID = 1
	deadline = big.NewInt(1_800_000_000)
	pairs = []store.Verdict{
		{Address: common.HexToAddress("0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"), Weight: 1},  // WETH
		{Address: common.HexToAddress("0xdAC17F958D2ee523a2206206994597C13D831ec7"), Weight: -1}, // USDT
		{Address: common.HexToAddress("0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"), Weight: 1},  // USDC
	}
	return
}

func buildVerdictFixture(t *testing.T) verdictFixture {
	t.Helper()
	keyHex, chainID, deadline, pairs := fixtureInputs()
	key, err := crypto.HexToECDSA(keyHex[2:])
	if err != nil {
		t.Fatal(err)
	}
	account := crypto.PubkeyToAddress(key.PublicKey)
	digest := verdictDigest(pairs)
	h, err := verdictDigestToSign(account, chainID, digest, deadline)
	if err != nil {
		t.Fatal(err)
	}
	sig, err := crypto.Sign(h, key)
	if err != nil {
		t.Fatal(err)
	}
	sig[64] += 27 // as a wallet returns it

	vs := make([]verdictPairJSON, len(pairs))
	for i, p := range pairs {
		vs[i] = verdictPairJSON{Address: p.Address.Hex(), Weight: p.Weight}
	}
	body, _ := json.Marshal(verdictRequest{
		ChainID: chainID, Account: account.Hex(), Deadline: deadline.String(),
		Verdicts: vs, Signature: hexutil.Encode(sig),
	})
	types := map[string][]map[string]string{}
	for name, fields := range verdictTypes {
		for _, f := range fields {
			types[name] = append(types[name], map[string]string{"name": f.Name, "type": f.Type})
		}
	}
	return verdictFixture{
		Note: "Generated by go test ./internal/api -run VerdictFixture -update. " +
			"digest = keccak256(concat over pairs sorted by address ascending of address(20) || int8(weight)); " +
			"eip712_hash = keccak256(0x1901 || domainSeparator || hashStruct(Verdict)); " +
			"signature has v in {27, 28}. The page must reproduce digest and eip712_hash " +
			"from verdicts alone and recover account from signature.",
		PrivateKey:  keyHex,
		Account:     account.Hex(),
		ChainID:     chainID,
		Deadline:    deadline.String(),
		Verdicts:    vs,
		Domain:      map[string]string{"name": verdictDomain.Name, "version": verdictDomain.Version},
		Types:       types,
		Digest:      digest.Hex(),
		TypedHash:   hexutil.Encode(h),
		Signature:   hexutil.Encode(sig),
		RequestBody: body,
	}
}

// TestVerdictFixture pins the digest, the EIP-712 hash and the signature to
// testdata/verdict.json, which the page's implementation is checked against.
func TestVerdictFixture(t *testing.T) {
	want := buildVerdictFixture(t)
	raw, err := json.MarshalIndent(want, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	raw = append(raw, '\n')
	path := filepath.Join("testdata", "verdict.json")
	if *updateVerdictFixture {
		if err := os.MkdirAll("testdata", 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, raw, 0o644); err != nil {
			t.Fatal(err)
		}
		t.Log("verdict.json rewritten; re-check the page's verdict signer against it")
		return
	}
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s (run with -update to create it): %v", path, err)
	}
	if !bytes.Equal(got, raw) {
		t.Fatalf("%s is stale: the digest or the typed data changed. If that was deliberate, "+
			"re-run with -update and re-check the page.\n--- want\n%s\n--- got\n%s", path, raw, got)
	}
	// And the fixture's signature really does recover to its account.
	var f verdictFixture
	if err := json.Unmarshal(got, &f); err != nil {
		t.Fatal(err)
	}
	deadline, _ := new(big.Int).SetString(f.Deadline, 10)
	who, err := recoverVerdictSigner(common.HexToAddress(f.Account), f.ChainID, common.HexToHash(f.Digest), deadline, common.FromHex(f.Signature))
	if err != nil || who != common.HexToAddress(f.Account) {
		t.Fatalf("fixture signature recovers to %s, %v; want %s", who.Hex(), err, f.Account)
	}
}

// The digest is order-independent on input and byte-exact on output.
func TestVerdictDigest(t *testing.T) {
	a := common.HexToAddress("0x0000000000000000000000000000000000000001")
	b := common.HexToAddress("0x0000000000000000000000000000000000000002")
	want := crypto.Keccak256Hash(append(append(append(a.Bytes(), 0x01), b.Bytes()...), 0xff))
	if got := verdictDigest([]store.Verdict{{Address: b, Weight: -1}, {Address: a, Weight: 1}}); got != want {
		t.Fatalf("digest = %s, want %s", got.Hex(), want.Hex())
	}
	if got := verdictDigest([]store.Verdict{{Address: a, Weight: 1}, {Address: b, Weight: -1}}); got != want {
		t.Fatal("input order changed the digest")
	}
	if verdictDigest([]store.Verdict{{Address: a, Weight: -1}, {Address: b, Weight: 1}}) == want {
		t.Fatal("swapping the weights left the digest unchanged")
	}
	if verdictDigest(nil) != crypto.Keccak256Hash(nil) {
		t.Fatal("an empty verdict should digest as keccak256 of nothing")
	}
}

// A wallet signs the EIP-712 digest and returns v in {27, 28}; the verifier must
// recover the account from exactly that, and from nothing else.
func TestVerdictSignatureRecovers(t *testing.T) {
	key, _ := crypto.GenerateKey()
	account := crypto.PubkeyToAddress(key.PublicKey)
	digest := crypto.Keccak256Hash([]byte("pairs"))
	deadline := big.NewInt(1_800_000_000)

	h, err := verdictDigestToSign(account, 8453, digest, deadline)
	if err != nil {
		t.Fatal(err)
	}
	sig, _ := crypto.Sign(h, key)
	sig[64] += 27

	if got, err := recoverVerdictSigner(account, 8453, digest, deadline, sig); err != nil || got != account {
		t.Fatalf("recovered %s, %v; want %s", got.Hex(), err, account.Hex())
	}
	// Another chain, another deadline: a different message, and the same
	// signature no longer recovers to the account.
	if got, _ := recoverVerdictSigner(account, 1, digest, deadline, sig); got == account {
		t.Fatal("a signature over another chain recovered to the account")
	}
	if got, _ := recoverVerdictSigner(account, 8453, digest, big.NewInt(1_800_000_001), sig); got == account {
		t.Fatal("a signature over another deadline recovered to the account")
	}
	if _, err := recoverVerdictSigner(account, 8453, digest, deadline, sig[:64]); err == nil {
		t.Fatal("a 64-byte signature was accepted")
	}
	// A Hint signature over the same fields is a different type and does not carry.
	hh, _ := hintDigestToSign(account, digest, deadline)
	hsig, _ := crypto.Sign(hh, key)
	hsig[64] += 27
	if got, _ := recoverVerdictSigner(account, 8453, digest, deadline, hsig); got == account {
		t.Fatal("a Hint signature was accepted as a Verdict")
	}
}
