package hintfilter

import (
	"bytes"
	"encoding/binary"
	"encoding/hex"
	"encoding/json"
	"flag"
	"os"
	"path/filepath"
	"testing"

	"github.com/ethereum/go-ethereum/common"
)

var update = flag.Bool("update", false, "rewrite the testdata vectors")

// The vectors are the contract between the Go writer and the JavaScript reader in
// web/index.html. Neither side is the specification; these files are. A change that
// alters the bytes has to be made deliberately, with -update, and the JS check has
// to be re-run against the result — which is the whole point, because two
// implementations of one format drift in silence otherwise. internal/lens/wire.go
// exists because of the same failure mode.
//
// Each case pins three separate things, so a mismatch says which one broke:
// subkey_hex pins Subkey, the per-probe key_hex pins Key, and the file itself pins
// Build and Encode.

type vectorProbe struct {
	Parts  []string `json:"parts_hex"`
	KeyHex string   `json:"key_hex"`
}

type vectorCase struct {
	Name      string        `json:"name"`
	File      string        `json:"file"`
	SecretHex string        `json:"secret_hex"`
	ChainID   uint64        `json:"chain_id"`
	Kind      uint8         `json:"kind"`
	Structure uint8         `json:"structure"`
	Blinded   bool          `json:"blinded"`
	SubkeyHex string        `json:"subkey_hex"`
	Members   []vectorProbe `json:"members"`
	Absent    []vectorProbe `json:"absent"`
}

type vectorFile struct {
	Note  string       `json:"note"`
	Cases []vectorCase `json:"cases"`
}

// probeBytes makes a deterministic 20-byte value, shaped like an address because
// that is what every real key is.
func probeBytes(tag byte, i int) []byte {
	b := make([]byte, 20)
	b[0] = tag
	binary.BigEndian.PutUint64(b[12:], uint64(i))
	return b
}

func buildVectors(t *testing.T) (vectorFile, map[string][]byte) {
	t.Helper()

	specs := []struct {
		name      string
		secret    []byte
		chainID   uint64
		kind      Kind
		structure Structure
		blinded   bool
		n         int
		desc      []byte
		bloomBits uint32
		interop   bool
	}{
		// Public, small: the structure a browser can also build.
		{"public-sorted", PublicSecret, 1, KindToken, StructureSortedU64, false, 64, nil, 0, false},
		// Public, large: forces the fuse path, and with enough keys that the
		// segment indices exercise the 64-bit multiply a JS reader must do with
		// BigInt rather than Number.
		{"public-fuse", PublicSecret, 1, KindAccountToken, StructureFuse8, false, 20_000, nil, 0, false},
		// Blinded: pins the subkey derivation across languages, which is the part
		// that silently produces a filter nobody can read if it drifts.
		{"blinded-sorted", []byte("test vector secret"), 8453, KindToken, StructureSortedU64, true, 64,
			[]byte(`{"kdf":"eip191","account":"0x0000000000000000000000000000000000000001","message":"evmscan/xorf/v1"}`), 0, false},
		// One slot, spanning chains. The keys are over ERC-7930 preimages, so the
		// chain is inside what is hashed and the subkey binds no chain at all
		// (chainID 0). This is the shape a per-account hint is published in, and it
		// pins the three things most likely to drift: the 7930 encoding, the
		// Kirsch-Mitzenmacher probe, and the bitmap byte order.
		{"public-bloom-interop", PublicSecret, 0, KindInterop, StructureBloom, false, 48, nil, 256, true},
	}

	// Chains a cross-chain vector spreads its keys over, so the preimage's minimal
	// big-endian chain reference is exercised at one, two and three bytes.
	interopChains := []uint64{1, 10, 8453, 42161, 11155111}

	out := vectorFile{
		Note: "Generated by go test ./internal/hintfilter -update. " +
			"Both the Go and the JavaScript reader must reproduce every key_hex and " +
			"agree on every member/absent verdict. Do not edit by hand.",
	}
	files := map[string][]byte{}

	for _, s := range specs {
		sub := Subkey(s.secret, s.chainID, s.kind)

		// What actually gets hashed after the subkey: a bare 20-byte address for the
		// per-chain kinds, an ERC-7930 interoperable address for the cross-chain one.
		preimage := func(tag byte, i int) []byte {
			addr := probeBytes(tag, i)
			if !s.interop {
				return addr
			}
			return Interop7930(interopChains[i%len(interopChains)], common.BytesToAddress(addr))
		}

		var keys []uint64
		var members []vectorProbe
		for i := range s.n {
			p := preimage(0xAA, i)
			k := Key(sub, p)
			keys = append(keys, k)
			// Record a sample rather than all 20,000; the file stays readable and
			// the coverage is identical.
			if len(members) < 16 {
				members = append(members, vectorProbe{
					Parts:  []string{"0x" + hex.EncodeToString(p)},
					KeyHex: hexU64(k),
				})
			}
		}

		f, err := Build(keys, Meta{
			Structure: s.structure, Blinded: s.blinded, BloomBits: s.bloomBits,
			ChainID: s.chainID, Kind: s.kind, EpochID: -1, Desc: s.desc,
		})
		if err != nil {
			t.Fatalf("%s: Build: %v", s.name, err)
		}

		// Absent probes are chosen, not assumed. A bloom sized for one slot says yes
		// to roughly one key in six, so taking the first sixteen non-members would
		// pin two or three false positives as "must answer no", and any correct
		// reader would fail on them. Ask the filter which ones it actually rejects
		// and pin those: every conforming reader must then agree.
		var absent []vectorProbe
		for i := 0; len(absent) < 16 && i < 4096; i++ {
			p := preimage(0xBB, i)
			k := Key(sub, p)
			if f.Contains(k) {
				continue
			}
			absent = append(absent, vectorProbe{
				Parts:  []string{"0x" + hex.EncodeToString(p)},
				KeyHex: hexU64(k),
			})
		}
		enc, err := f.Encode()
		if err != nil {
			t.Fatalf("%s: Encode: %v", s.name, err)
		}

		name := s.name + ".xorf"
		files[name] = enc
		out.Cases = append(out.Cases, vectorCase{
			Name: s.name, File: name,
			SecretHex: "0x" + hex.EncodeToString(s.secret),
			ChainID:   s.chainID, Kind: uint8(s.kind), Structure: uint8(s.structure),
			Blinded: s.blinded, SubkeyHex: "0x" + hex.EncodeToString(sub[:]),
			Members: members, Absent: absent,
		})
	}
	return out, files
}

func hexU64(v uint64) string {
	var b [8]byte
	binary.BigEndian.PutUint64(b[:], v)
	return "0x" + hex.EncodeToString(b[:])
}

func TestVectors(t *testing.T) {
	spec, files := buildVectors(t)
	manifest, err := json.MarshalIndent(spec, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	manifest = append(manifest, '\n')

	dir := "testdata"
	if *update {
		for name, b := range files {
			if err := os.WriteFile(filepath.Join(dir, name), b, 0o644); err != nil {
				t.Fatal(err)
			}
		}
		if err := os.WriteFile(filepath.Join(dir, "vectors.json"), manifest, 0o644); err != nil {
			t.Fatal(err)
		}
		t.Log("vectors rewritten; re-run the browser check in web/index.html against them")
		return
	}

	got, err := os.ReadFile(filepath.Join(dir, "vectors.json"))
	if err != nil {
		t.Fatalf("read vectors.json (run with -update to create it): %v", err)
	}
	if !bytes.Equal(got, manifest) {
		t.Error("vectors.json is stale: the key derivation or the metadata changed. " +
			"If that was deliberate, re-run with -update and re-check the JS reader.")
	}

	for name, want := range files {
		got, err := os.ReadFile(filepath.Join(dir, name))
		if err != nil {
			t.Fatalf("read %s (run with -update to create it): %v", name, err)
		}
		if !bytes.Equal(got, want) {
			t.Errorf("%s is stale: the encoding changed. If that was deliberate, "+
				"re-run with -update and re-check the JS reader.", name)
		}
	}
}

// TestVectorsSelfConsistent checks the vectors say what they claim, so a broken
// generator cannot quietly produce a fixture that pins the wrong behaviour.
func TestVectorsSelfConsistent(t *testing.T) {
	raw, err := os.ReadFile("testdata/vectors.json")
	if err != nil {
		t.Skipf("no vectors yet: %v", err)
	}
	var spec vectorFile
	if err := json.Unmarshal(raw, &spec); err != nil {
		t.Fatal(err)
	}

	for _, c := range spec.Cases {
		t.Run(c.Name, func(t *testing.T) {
			b, err := os.ReadFile(filepath.Join("testdata", c.File))
			if err != nil {
				t.Fatal(err)
			}
			f, err := Decode(b)
			if err != nil {
				t.Fatalf("Decode: %v", err)
			}
			if f.ChainID != c.ChainID || uint8(f.Kind) != c.Kind ||
				uint8(f.Structure) != c.Structure || f.Blinded != c.Blinded {
				t.Errorf("decoded metadata disagrees with the manifest: %+v", f.Meta)
			}

			secret := mustHex(t, c.SecretHex)
			sub := Subkey(secret, c.ChainID, Kind(c.Kind))
			if "0x"+hex.EncodeToString(sub[:]) != c.SubkeyHex {
				t.Fatalf("Subkey = %x, manifest says %s", sub, c.SubkeyHex)
			}

			for _, p := range c.Members {
				k := Key(sub, mustHex(t, p.Parts[0]))
				if hexU64(k) != p.KeyHex {
					t.Errorf("Key = %s, manifest says %s", hexU64(k), p.KeyHex)
				}
				if !f.Contains(k) {
					t.Errorf("member %s not in the filter", p.Parts[0])
				}
			}
			for _, p := range c.Absent {
				k := Key(sub, mustHex(t, p.Parts[0]))
				if hexU64(k) != p.KeyHex {
					t.Errorf("Key = %s, manifest says %s", hexU64(k), p.KeyHex)
				}
				if f.Contains(k) && c.Structure == uint8(StructureSortedU64) {
					// sorted-u64 is exact, so a hit here is a real bug rather than
					// the false positive a fuse filter is allowed.
					t.Errorf("absent %s reported present by an exact structure", p.Parts[0])
				}
			}
		})
	}
}

func mustHex(t *testing.T, s string) []byte {
	t.Helper()
	b, err := hex.DecodeString(s[2:])
	if err != nil {
		t.Fatalf("bad hex %q: %v", s, err)
	}
	return b
}
