/**
 * The name resolver, against blobs go-ethereum packed from the Universal Resolver ABI.
 *
 * Generated by internal/ens/mirror_fixtures_test.go, which also asserts the file is
 * in step with the Go side, so an encoding that drifts on either end fails there
 * before it can resolve the wrong address here.
 */

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import { bytesToHex, normalizeHex, type Hex } from "../src/merkle.js";
import {
  coinTypeFor,
  decodeResolveAddr,
  decodeReverse,
  dnsEncode,
  encodeResolveAddr,
  encodeReverse,
  NameNotFoundError,
  namehash,
  normalizeName,
  OffchainNameError,
  resolveName,
  ResolverError,
  revertData,
  ReverseMismatchError,
  reverseName,
  UNIVERSAL_RESOLVER,
} from "../src/names.js";
import type { EthCall } from "../src/registry.js";

interface NamesFixture {
  universal_resolver: Hex;
  names: { name: string; hash: Hex; dns: Hex }[];
  resolve: {
    name: string;
    address: Hex;
    resolver: Hex;
    calldata: Hex;
    returndata: Hex;
    zero_returndata: Hex;
  };
  reverse: {
    address: Hex;
    coin_type: string;
    name: string;
    resolver: Hex;
    reverse_resolver: Hex;
    calldata: Hex;
    returndata: Hex;
    empty_returndata: Hex;
  };
  reverts: {
    resolver_not_found: Hex;
    offchain_lookup: Hex;
    offchain_urls: string[];
    reverse_mismatch: Hex;
    reverse_mismatch_name: string;
    resolver_error: Hex;
    unsupported_profile: Hex;
  };
}

const fixture = JSON.parse(
  readFileSync(fileURLToPath(new URL("../testdata/names.json", import.meta.url)), "utf8"),
) as NamesFixture;

const UR = normalizeHex(fixture.universal_resolver, 20);

/** An eth_call that reverts the way a raw JSON-RPC client surfaces it. */
function reverting(data: Hex): EthCall {
  return async () => {
    throw Object.assign(new Error("execution reverted"), { data });
  };
}

describe("names", () => {
  it("uses the canonical Universal Resolver", () => {
    expect(UNIVERSAL_RESOLVER).toBe(UR);
  });

  it("hashes and wire-encodes exactly as internal/ens does", () => {
    for (const v of fixture.names) {
      expect(namehash(v.name)).toBe(normalizeHex(v.hash, 32));
      expect(bytesToHex(dnsEncode(v.name))).toBe(normalizeHex(v.dns));
    }
  });

  it("normalizes the way the Go side and the page do", () => {
    expect(normalizeName(" Vitalik.ETH. ")).toBe("vitalik.eth");
    expect(normalizeName("café.eth")).toBe(normalizeName("café.eth"));
    for (const bad of ["", ".", "a..eth", "a b.eth", "a\tb.eth", `${"a".repeat(64)}.eth`]) {
      expect(() => normalizeName(bad)).toThrow();
    }
  });

  it("derives coin types per ENSIP-19", () => {
    expect(coinTypeFor(1n)).toBe(60n);
    expect(coinTypeFor(11155111n)).toBe(60n);
    expect(coinTypeFor(8453n)).toBe(0x80000000n | 8453n);
  });
});

describe("forward resolution", () => {
  const f = fixture.resolve;

  it("encodes resolve(dns, addr(node)) exactly as the ABI does", () => {
    expect(encodeResolveAddr(f.name)).toBe(normalizeHex(f.calldata));
  });

  it("decodes (bytes result, address resolver)", () => {
    const got = decodeResolveAddr(f.returndata);
    expect(got.address).toBe(normalizeHex(f.address, 20));
    expect(got.resolver).toBe(normalizeHex(f.resolver, 20));
  });

  it("resolves through the injected call", async () => {
    const call: EthCall = async (to, data) => {
      expect(to).toBe(UR);
      expect(data).toBe(normalizeHex(f.calldata));
      return f.returndata;
    };
    const r = await resolveName(call, ` ${f.name.toUpperCase()} `);
    expect(r.address).toBe(normalizeHex(f.address, 20));
    expect(r.name).toBe(f.name);
    expect(r.resolver).toBe(normalizeHex(f.resolver, 20));
  });

  it("treats a zero address as not found", async () => {
    await expect(resolveName(async () => f.zero_returndata, f.name)).rejects.toBeInstanceOf(
      NameNotFoundError,
    );
  });

  it("reads ResolverNotFound as not found", async () => {
    await expect(
      resolveName(reverting(fixture.reverts.resolver_not_found), "nobody.eth"),
    ).rejects.toBeInstanceOf(NameNotFoundError);
  });

  it("reports an offchain name with its gateways and does not follow them", async () => {
    const err = await resolveName(reverting(fixture.reverts.offchain_lookup), f.name).catch(
      (e: unknown) => e,
    );
    expect(err).toBeInstanceOf(OffchainNameError);
    expect((err as OffchainNameError).urls).toEqual(fixture.reverts.offchain_urls);
  });

  it("surfaces any other revert by selector", async () => {
    const err = await resolveName(reverting(fixture.reverts.unsupported_profile), f.name).catch(
      (e: unknown) => e,
    );
    expect(err).toBeInstanceOf(ResolverError);
    expect((err as ResolverError).selector).toBe(fixture.reverts.unsupported_profile.slice(0, 10));
  });

  it("rethrows a transport failure untouched", async () => {
    const boom = new Error("socket hang up");
    await expect(
      resolveName(async () => {
        throw boom;
      }, f.name),
    ).rejects.toBe(boom);
  });

  it("finds revert data wherever a transport put it", () => {
    const d = fixture.reverts.resolver_error;
    expect(revertData({ data: d })).toBe(d);
    expect(revertData({ cause: { error: { data: d } } })).toBe(d);
    expect(revertData(new Error(`execution reverted: ${d}`))).toBe(d);
    expect(revertData(new Error("connection refused"))).toBeNull();
  });
});

describe("reverse resolution", () => {
  const f = fixture.reverse;

  it("encodes reverse(address, coinType) exactly as the ABI does", () => {
    expect(encodeReverse(f.address, BigInt(f.coin_type))).toBe(normalizeHex(f.calldata));
  });

  it("decodes (string, address, address)", () => {
    const got = decodeReverse(f.returndata);
    expect(got.name).toBe(f.name);
    expect(got.resolver).toBe(normalizeHex(f.resolver, 20));
    expect(got.reverseResolver).toBe(normalizeHex(f.reverse_resolver, 20));
  });

  it("answers the primary name through the injected call", async () => {
    const call: EthCall = async (to, data) => {
      expect(to).toBe(UR);
      expect(data).toBe(normalizeHex(f.calldata));
      return f.returndata;
    };
    const r = await reverseName(call, f.address, 1n);
    expect(r?.name).toBe(f.name);
  });

  it("answers null for no record", async () => {
    expect(await reverseName(async () => f.empty_returndata, f.address, 1n)).toBeNull();
    expect(
      await reverseName(reverting(fixture.reverts.resolver_not_found), f.address, 1n),
    ).toBeNull();
  });

  it("distinguishes a contradicted claim from no claim", async () => {
    const err = await reverseName(reverting(fixture.reverts.reverse_mismatch), f.address, 1n).catch(
      (e: unknown) => e,
    );
    expect(err).toBeInstanceOf(ReverseMismatchError);
    expect((err as ReverseMismatchError).primary).toBe(fixture.reverts.reverse_mismatch_name);
  });
});
