/**
 * Holds the TypeScript port to the bytes Go produces.
 *
 * The fixtures in ../testdata are generated by internal/snapshot/fixtures_test.go,
 * which is the side that already agrees with the Solidity verifier. If a case here
 * fails, this port is wrong — not the fixture. Regenerate only when the Go
 * encoding itself changed, which also means changing HintRegistry.
 */

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import {
  assetKey,
  assetsHash,
  buildRoot,
  coverageLeaf,
  hashPair,
  leafHash,
  normalizeHex,
  verifyInclusion,
  ZERO_HASH,
  type Hex,
} from "../src/merkle.js";
import { parseHeader, parseSnapshot, rootsOf, sortLeaves } from "../src/snapshot.js";

const testdata = (name: string): string =>
  readFileSync(fileURLToPath(new URL(`../testdata/${name}`, import.meta.url)), "utf8");

/**
 * Every uint64 in the fixture files is a decimal *string*, not a JSON number. That
 * is not a style choice: JSON.parse rounds anything above 2^53, and the vector that
 * exists to catch exactly that mistake would be the first casualty of it.
 */
interface Vectors {
  assets_hash: { why: string; assets: Hex[]; hash: Hex }[];
  leaf_hash: { why: string; account: Hex; chain_id: string; assets_hash: Hex; leaf: Hex }[];
  asset_key: { chain_id: string; asset: Hex; key: Hex }[];
  coverage_leaf: { asset_key: Hex; from_block: string; to_block: string; leaf: Hex }[];
  root: { why: string; leaves: Hex[]; root: Hex }[];
}

interface Manifest {
  format: string;
  cases: {
    name: string;
    why: string;
    file: string;
    chain_id: string;
    leaves: number;
    assets: number;
    root: Hex;
    coverage_root: Hex;
  }[];
}

const vectors = JSON.parse(testdata("vectors.json")) as Vectors;
const manifest = JSON.parse(testdata("manifest.json")) as Manifest;

/**
 * Reads a document's chain id straight out of the header text.
 *
 * The manifest states it too, but a parser is being tested here — so the expected
 * value is taken from the raw bytes rather than from anything in ../src.
 */
function chainIdOf(file: string): bigint {
  const header = testdata(file).split("\n")[0]!;
  const match = /"chain_id":(\d+)/.exec(header);
  if (match === null) throw new Error(`no chain_id in ${file}`);
  return BigInt(match[1]!);
}

describe("primitives against the Go vectors", () => {
  it.each(vectors.assets_hash)("assetsHash: $why", ({ assets, hash }) => {
    expect(assetsHash(assets)).toBe(normalizeHex(hash, 32));
  });

  it.each(vectors.leaf_hash)("leafHash: $why", ({ account, chain_id, assets_hash, leaf }) => {
    expect(leafHash(account, BigInt(chain_id), assets_hash)).toBe(normalizeHex(leaf, 32));
  });

  it.each(vectors.asset_key)("assetKey on chain $chain_id", ({ chain_id, asset, key }) => {
    expect(assetKey(BigInt(chain_id), asset)).toBe(normalizeHex(key, 32));
  });

  it.each(vectors.coverage_leaf)(
    "coverageLeaf $from_block..$to_block",
    ({ asset_key, from_block, to_block, leaf }) => {
      expect(coverageLeaf(asset_key, BigInt(from_block), BigInt(to_block))).toBe(
        normalizeHex(leaf, 32),
      );
    },
  );

  it.each(vectors.root)("buildRoot: $why", ({ leaves, root }) => {
    expect(buildRoot(leaves)).toBe(normalizeHex(root, 32));
  });

  it("commits an empty tree to the zero hash", () => {
    expect(buildRoot([])).toBe(ZERO_HASH);
  });

  it("sorts the pair, so argument order cannot change a root", () => {
    const a = `0x${"11".repeat(32)}`;
    const b = `0x${"22".repeat(32)}`;
    expect(hashPair(a, b)).toBe(hashPair(b, a));
  });

  it("refuses a uint64 it cannot represent", () => {
    expect(() => leafHash(`0x${"00".repeat(20)}`, 2n ** 64n, ZERO_HASH)).toThrow(/uint64/);
  });

  it("rejects an address of the wrong length rather than padding it", () => {
    expect(() => assetsHash(["0xa1"])).toThrow(/expected 20 bytes/);
  });
});

describe("whole snapshot documents", () => {
  it("covers every case the Go side generated", () => {
    expect(manifest.cases.map((c) => c.name)).toEqual([
      "empty",
      "single",
      "even",
      "odd",
      "odd-deep",
      "messy-assets",
      "wide-chain-id",
    ]);
  });

  it.each(manifest.cases)("$name: $why", (c) => {
    const snapshot = parseSnapshot(testdata(c.file));

    // The roots this port rebuilds are the ones Go committed.
    expect(snapshot.root).toBe(normalizeHex(c.root, 32));
    expect(snapshot.coverageRoot).toBe(normalizeHex(c.coverage_root, 32));
    // And the ones the document itself claims, which is what a wallet compares
    // against the registry.
    expect(snapshot.root).toBe(snapshot.header.root);
    expect(snapshot.coverageRoot).toBe(snapshot.header.coverageRoot);

    expect(snapshot.leaves).toHaveLength(c.leaves);
    expect(snapshot.coverage).toHaveLength(c.assets);
    expect(snapshot.header.chainId).toBe(chainIdOf(c.file));
  });

  it("reads a chain id that a float would have rounded", () => {
    const wide = manifest.cases.find((c) => c.name === "wide-chain-id")!;
    const chainId = chainIdOf(wide.file);
    expect(chainId).toBe(0xfedcba9876543210n);
    // Why this case exists: as a float the chain id is indistinguishable from its
    // neighbour, so a parser that goes through JSON.parse's number hashes the wrong
    // leaf and blames the publisher for the mismatch.
    expect(Number(chainId)).toBe(Number(chainId - 1n));
    expect(chainId).not.toBe(chainId - 1n);
    expect(parseSnapshot(testdata(wide.file)).root).toBe(normalizeHex(wide.root, 32));
  });

  it("hashes a leaf's assets independently of order and duplication", () => {
    const messy = manifest.cases.find((c) => c.name === "messy-assets")!;
    const { leaves } = parseSnapshot(testdata(messy.file));
    const [first, second] = leaves;
    expect(first!.assets).toHaveLength(4); // as written: descending, one repeat
    expect(second!.assets).toHaveLength(3);
    expect(assetsHash(first!.assets)).toBe(assetsHash(second!.assets));
  });

  it("rebuilds the same root from rows held in memory", () => {
    for (const c of manifest.cases) {
      const snapshot = parseSnapshot(testdata(c.file));
      const rebuilt = rootsOf(snapshot.header.chainId, snapshot.coverage, snapshot.leaves);
      expect(rebuilt.root).toBe(snapshot.root);
      expect(rebuilt.coverageRoot).toBe(snapshot.coverageRoot);
    }
  });

  it("recovers the publisher's leaf order from an unordered set", () => {
    // This is the property a mirror depends on: rows come out of SQLite in
    // whatever order, and sortLeaves has to put them back into the sequence the
    // tree was built from.
    const c = manifest.cases.find((x) => x.name === "odd-deep")!;
    const snapshot = parseSnapshot(testdata(c.file));
    const shuffled = [...snapshot.leaves].reverse();

    expect(rootsOf(snapshot.header.chainId, [], shuffled).root).not.toBe(snapshot.root);
    expect(rootsOf(snapshot.header.chainId, [], sortLeaves(shuffled)).root).toBe(snapshot.root);
    expect(sortLeaves(shuffled)).toEqual(snapshot.leaves);
  });

  it("refuses a document whose leaf count disagrees with its header", () => {
    const doc = testdata("odd.ndjson").trimEnd().split("\n");
    expect(() => parseSnapshot(doc.slice(0, -1).join("\n"))).toThrow(/header says 3 leaves/);
  });

  it("refuses coverage rows interleaved with leaves", () => {
    const lines = testdata("odd.ndjson").trimEnd().split("\n");
    const reordered = [lines[0]!, lines[4]!, lines[1]!, lines[2]!, lines[3]!, lines[5]!];
    expect(() => parseSnapshot(reordered.join("\n"))).toThrow(/sections are ordered/);
  });

  it("refuses an unknown format", () => {
    expect(() => parseSnapshot('{"format":"evmscan-snapshot/2"}')).toThrow(/unknown snapshot format/);
  });

  it("says which field is not an integer, rather than failing to parse at all", () => {
    // The lossless pre-pass quotes bare integers. A fraction or an exponent has to
    // be consumed whole: emitting only the integer part leaves the remaining digits
    // to be re-quoted, which yields invalid JSON and a SyntaxError blaming the
    // document instead of the field.
    const header = testdata("single.ndjson").split("\n")[0]!;
    const withToBlock = (value: string): string => `${header.slice(0, -1)},"to_block":${value}}`;
    for (const value of ["1.5", "-2.25", "1e400"]) {
      expect(() => parseHeader(withToBlock(value)), value).toThrow(/to_block/);
    }
    // A fraction or exponent that names a whole number is still read as one —
    // proof the token was consumed whole and the JSON not corrupted on the way.
    for (const value of ["2e2", "2E+2", "200.0", "2.0e2"]) {
      expect(parseHeader(withToBlock(value)).toBlock, value).toBe(200n);
    }
  });
});

describe("inclusion proofs", () => {
  it("replays a proof the way the Solidity verifier does", () => {
    const leaves = vectors.root.find((v) => v.leaves.length === 5)!.leaves;
    const root = buildRoot(leaves);

    // Hand-built path for leaf 0 of a 5-leaf tree: sibling, then the aunt, then the
    // promoted subtree. Written out rather than generated, so a bug in a proof
    // builder cannot make this test agree with itself.
    const l = leaves.map((h) => normalizeHex(h, 32));
    const proof = [l[1]!, hashPair(l[2]!, l[3]!), l[4]!];
    expect(verifyInclusion(root, l[0]!, proof)).toBe(true);
    expect(verifyInclusion(root, l[1]!, proof)).toBe(false);
  });
});
